### ISSUE TITLE
new psf behavior update

### ISSUE THREAD

**Issue by adavak** [Secant1006/PSFExtractor#1]
E.G:
Windows10.0-KB5004567-x64-baseless_41fdbca3.cab | 41fdbca3d0868b158a332a744f5ede77d83f2e2e | 29.11 KiB
Windows10.0-KB5004567-x64-baseless_87afeecd.psf | 87afeecd1e0a587f16390eac4ee277269ef80e39 | 116.17 KiB
Windows10.0-KB5004567-x64_611502da.cab | 611502dae49fd21cc5f5c1b4c998d9e75cfe099a | 27.01 KiB

**Comment by Secant1006** [comment]
Actually, baseless PSFs aren't necessary for installing an update, although it could be supported in a future version, or maybe not. Currently you can just delete any update which contains "baseless".

**Comment by adavak** [comment]
del the small one baseless and place others cab and psf alone, that's works.

**Comment by abbodi1406** [comment]
> 
> 
> del the small one baseless and place others cab and psf alone, that's works.

Windows10.0-KB5004567-x64_611502da.cab is already independant, it does not need the psf
baseless cab/psf works together
